# 子任务列表数量上限
max_sub_task_count: 3
# 策略
planning_strategy: "nearest_first"  # nearest_first, custom_logic

# 循环频率（Hz）
loop_rate: 10

# 订阅话题
detection_topic: /object_detection/detected_objects
sub_task_result_topic: /motion_control/sub_task_result
info_topic: /ctrl/info

# 发布话题
task_topic: /task_planning/task
sub_task_topic: /task_planning/sub_task
